// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHdW2OIvR1orqI6LUpUz1WuzkJtgVkWOg',
    appId: '1:973958946389:web:8435e4d5276acffad9fedc',
    messagingSenderId: '973958946389',
    projectId: 'fir-login-46493',
    authDomain: 'fir-login-46493.firebaseapp.com',
    storageBucket: 'fir-login-46493.appspot.com',
    measurementId: 'G-JG7Y21SL73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjGWefYyYBTJM1U6ThyVpJlCq9ItucbN8',
    appId: '1:973958946389:android:7dfa1f0789b5bdd8d9fedc',
    messagingSenderId: '973958946389',
    projectId: 'fir-login-46493',
    storageBucket: 'fir-login-46493.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBophDh4UqUt2Alkwmy3sifQnMcsd4CxpI',
    appId: '1:973958946389:ios:8576c41999223194d9fedc',
    messagingSenderId: '973958946389',
    projectId: 'fir-login-46493',
    storageBucket: 'fir-login-46493.appspot.com',
    iosClientId: '973958946389-souae1favemle8sdovps976ra6hupukf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaselogingoogle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBophDh4UqUt2Alkwmy3sifQnMcsd4CxpI',
    appId: '1:973958946389:ios:8576c41999223194d9fedc',
    messagingSenderId: '973958946389',
    projectId: 'fir-login-46493',
    storageBucket: 'fir-login-46493.appspot.com',
    iosClientId: '973958946389-souae1favemle8sdovps976ra6hupukf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaselogingoogle',
  );
}
